controllers:
  resource: ../src/Controller/
  type: annotation

kernel:
  resource: ../src/Kernel.php
  type: annotation

#El nombre solo es referencial
app_lucky_number:
  #Ruta de la barra de direciones a partir del home /
  path: /lucky/number
  #La ruta del controlador y el nombre de la funcion que se va ejecutar cuando ya este en esa ruta
  controller: App\Controller\LuckyController::numero

blog_list:
  path: /blog
  # the controller value has the format 'controller_class::method_name'
  controller: App\Controller\BlogController::list
